name: quantcore.glm
channels:
  - ***REMOVED***
  - conda-forge
  - nodefaults
dependencies:
  - altair
  - black
  - c-compiler
  - cxx-compiler
  - cython
  - dask-ml
  - flake8
  - git_root
  - h2o-py
  - ipdb
  - ipython
  - jinja2==2.11.3
  - johnlees-glmnet_python
  - jupyterlab
  - jupytext
  - libblas>=0=*mkl
  - libpysal
  - line_profiler
  - make
  - mako
  - memory_profiler
  - mkl-include
  - nbclassic=0.2.7
  - nbsphinx=0.8.3
  - numexpr
  - openjdk
  - openml
  - pandas
  - pip
  - pre-commit
  - pyarrow
  - pyshp
  - pytest
  - pytest-xdist
  - quantcore.matrix>=2.0.1
  - rpy2
  - scikit-learn
  - setuptools_scm
  - shapely
  - sparse_dot_mkl>=0.5.3
  - sphinx=3.5.3
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc
  - tqdm
  - xsimd
