name: CI
on:
  push:
    branches:
      - master

jobs:
  macos:
    name: "MacOS - tests - Python ${{ matrix.PYTHON_VERSION }}"
    runs-on: macos-latest
    env:
      CI: True
      ***REMOVED***: ${{ secrets.***REMOVED*** }}
      ***REMOVED***: ${{ secrets.***REMOVED*** }}
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: true
      matrix:
        PYTHON_VERSION: ['3.7']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
      - name: Create .condarc
        shell: bash -l {0}
        run: |
          sed -ie "s/***REMOVED***/${***REMOVED***}/g" .github/workflows/.condarc
          sed -ie "s/***REMOVED***/${***REMOVED***}/g" .github/workflows/.condarc
        env:
          ***REMOVED***: ${{ secrets.***REMOVED*** }}
          ***REMOVED***: ${{ secrets.***REMOVED*** }}
      - uses: conda-incubator/setup-miniconda@35d1405e78aa3f784fe3ce9a2eb378d5eeb62169
        with:
          miniforge-variant: Mambaforge
          miniforge-version: 4.10.0-0
          use-mamba: true
          condarc-file: .github/workflows/.condarc
      - name: Run Unit Tests
        shell: bash -l {0}
        run: ./.github/workflows/macos.sh

